---
- name: get_package
#  hosts: test
  hosts: "{{host}}"
  remote_user: root



  tasks:
#      register: command_out
#    - debug: var=command_out
#    - shell: echo 'start----'
#        - name: "download package..."
#      - name: mv_old
#        command: src="{{client_path}}"/"{{package_name}}" dest="{{client_path}}"/"{{package_name}}".bak
      - name: download
#        command: mv "{{client_path}}"/"{{package_name}}" "{{client_path}}"/"{{package_name}}".bak
        command: wget -O tmp/"{{package_name}}" "{{package_url}}"
        notify: tars

  handlers:
    - name: tars
      command:  tar zxvf tmp/"{{package_name}}" -C "{{client_path}}"